export const PRODUCT_VALID_CODES = ['BARCODE_INTERNAL', 'BARCODE_PROVIDER', 'QR_INTERNAL'] as const
export const PRODUCT_EVENTS = ['CREATED_AT', 'PRICE_COST_CHANGE', 'PRICE_SALE_CHANGE', 'STOCK_ADJUSTMENT', 'DESCRIPTION_CHANGE'] as const
