export const PRODUCT_VALID_CODES = ['BARCODE_INTERNAL', 'BARCODE_PROVIDER', 'QR_INTERNAL'] as const
export const PRODUCT_EVENTS = {
  CREATED_AT: 'CREATED_AT',
  PRICE_COST_CHANGE: 'PRICE_COST_CHANGE',
  PRICE_SALE_CHANGE: 'PRICE_SALE_CHANGE',
  STOCK_ADJUSTMENT: 'STOCK_ADJUSTMENT',
  DESCRIPTION_CHANGE: 'DESCRIPTION_CHANGE'
} as const
export const PRODUCT_EVENT_LIST = Object.values(PRODUCT_EVENTS)
export const INITIAL_EVENT_VALUE = 'none'
